### ISSUE TITLE
Disable past dates

### ISSUE THREAD

**Issue by brunoDegaspare** [KidSysco/jquery-ui-month-picker#11]
Is it possible to disable past months once first month is set?

**Comment by KidSysco** [comment]
Hi Bruno,

There is not currently a way to do this. However, mrj has a fork where he has been working on max and min date limits and he has it working pretty well. I think he is about ready to merge but you might check with him and see.

https://github.com/mrj/jquery-ui-month-picker

Using that setting, you could write a bit of JS that would just set the min date on the control based on the user input in order to get what you are looking for!

Pretty cool idea!

I will close this out once mrj merges.

-kid

**Comment by KidSysco** [comment]
I think Benjamins fix addresses this, if not go ahead and open another issue.
