### ISSUE TITLE
The plugin no longer works on IE8

### ISSUE THREAD

**Issue by mareek** [KidSysco/jquery-ui-month-picker#34]
When used in IE8 the folowing exception is thrown:
"Object doesn't support property or method 'indexOf'"

The error occurs since this commit:
https://github.com/KidSysco/jquery-ui-month-picker/commit/f5c5a75dabe5c776552185a8259abffd95fa1a03

**Comment by KidSysco** [comment]
Yeap, that is what my tests show too, good find! Thanks for reporting this!

It should be a quick fix, I will post back when it is ready for IE 8.

**Comment by KidSysco** [comment]
Now I just gotta see if I can fix it before Benjamin does! He is so fast, pretty hard to beat! lol!

**Comment by benjamin-albert** [comment]
I run the plugin at work in IE 8 compatibility (aka enterprise) mode by adding an Array.indexOf polyfill. 

I guess we can replace the use of index of with jQuery's $.inArray() function.

@KidSysco I have enough IE 8 enterprise mode nonsense at work (plus I don't feel like asking for someone else's Windows machine for this) so please fix this issue and I'll pull your changes into my 3.0 branch.

**Comment by benjamin-albert** [comment]
@KidSysco Can you tell me the img button test passes in IE 8?

If it's failing because the img attribute's value is the absolute path, please see if you can work around IE 8's lack of support of DOM attributes.

I'm really curious about this please update me about this.

**Comment by KidSysco** [comment]
ok I will keep you posted.

**Comment by KidSysco** [comment]
I used to have IE 8 issues at work (US Army). Then I got a new job! I am much happier now but I still feel for folks who have to deal with the IE struggle. Also Benjamin has been setting us up really nicely, so I think that my latest commits will get reflected on the JSFiddle demo due to the CDN we are using in JSFIddle now. That is so cool! 

OK I will take a quick look at your img button and see how it fares in the IE conundrum.

**Comment by KidSysco** [comment]
OK Benjamin... I kinda forgot where we are working out of but I went ahead and tested your 3.0 branch in IE 11. I think this is right because the tests are looking for the menu to be displayed as inline-block but now they are showing as block. I think that is expected and easy to fix. However, this issue should be showing on all browsers. So you probably know about that one.

If I try to test the 3.0 branch in IE 8, then tests break due to indexOf again. 

Perhaps you want to merge my latest commits, then have me re-test again.

You have been such a huge help around this repo Benjamin,your wish, is my command. If you need me to test in IE and make fixes, then I am there for you!

I really enjoy working with you, I would work with you any day. Shoot I would work FOR you any day. So if you ever need anything, even on another project, Let me know.

I am closing this issue out now, I just tried to test JSFiddle in IE 8 and it breaks down heavily. Running tests in IE 8 is going to be the only way we see this. Since we are both on Mac's it sucks, which is fine, leave it to me! I have good VMs setup in the cloud and such.

**Comment by mareek** [comment]
That was a really quick fix indeed !
Thank you very much

**Comment by benjamin-albert** [comment]
I've merged your changes into my 3.0 branch.

All tests are passing in PhantomJS, Firefox Developer Edition, Chrome and Safari.

@KidSysco Please run the tests in IE and tell me whats the verdict.

Thanks.

**Comment by KidSysco** [comment]
I have never been so happy to serve, I will let you know later today!

**Comment by KidSysco** [comment]
I just sync'd and re-tested your 3.0 branch. I do not see that the tests pass in PhantomJS.

It has to do with the menu showing as block instead of inline-block.

Am I doing something wrong?

**Comment by benjamin-albert** [comment]
You're right, I accidentally pushed a commit for the in progress work on the year title button which I haven't adjusted the internals (and possibly unit test) for this big change.

From now on I will only push code that passes the unit tests to the [3.0_prototype](https://github.com/benjamin-albert/jquery-ui-month-picker/tree/3.0_prototype) branch and I will have another branch [alpha_4_progress](https://github.com/benjamin-albert/jquery-ui-month-picker/tree/alpha_4_progress) which will have in progress work that might not pass the unit tests.

I've reset the [3.0_prototype](https://github.com/benjamin-albert/jquery-ui-month-picker/tree/3.0_prototype) one commit back to the merge commit with you which passes the tests.

So take a look at the year title button and tell me what you think (yes I know everything else is broken I'm still working on it) and then fetch from my 3.0 branch again and run the tests again.

**Comment by KidSysco** [comment]
OK here it is.

The transparent year button was working great in all browsers in the previous version of the 3.0 branch, despite the unit test errors.

Then I fetched updated code from the 3.0 branch and ran all tests again.

IE 8 - 11 the button still works great despite the test errors that are simpler now.

Edge - all tests pass just as if it were running in a PhantomJS instance.

Also, there was one indexOf issue in IE8.

If you want to know that the transparent year button is working... it is working very well!

let me know if you need anything else.

**Comment by benjamin-albert** [comment]
Do the tests pass in IE if you fetch the  [3.0_prototype](https://github.com/benjamin-albert/jquery-ui-month-picker/tree/3.0_prototype) branch, which should not include the transparent jump years button?

**Comment by KidSysco** [comment]
Sorry I got confused.

I think I tested the 3.0_prototype branch but I didnt recognize it. I
thought I was testing the 3.0 branch but I can no longer find the 3.0
branch.

So I just ran all tests again against the 3.0_prototype branch and it had
all of the exact same results as I posted before...

All tests pass in Edge just as they do in PhantomJs.

All versions of IE are showing that tests expect to see the menu as block
but instead are seeing it as inline-block. However, all buttons and
features appear to work correctly despite the failed tests.

IE 8 shows a single indexOf error and the block vs. inline-block errors.

Let me know if you need anything else.
