### ISSUE TITLE
Possible enhancements?

### ISSUE THREAD

**Issue by ppritcha** [KidSysco/jquery-ui-month-picker#5]
Nice plugin...it works almost exactly the way I want.  Would it be possible to add two options like jqueryui's datepicker:

buttonImage -- to allow me to set the icon's image
showOn: "both" -- Controls when the picker appears.  The picker can appear when the field receives focus ("focus"), when the icon button is clicked ("button"), or when either event occurs ("both").  Currently if the icon is shown, there doesn't appear to be a way to make the picker appear on focus.

Thanks!

**Comment by chrisbean33** [comment]
good plugin, and works well with html5 month input.  What I would like to see is the ability to set: Min, Max, Start values or atleast not allow historic values.  keep up the good work..

**Comment by mrj** [comment]
This was the best month selector I found for my purposes.

I've implemented some enhancements:
* The selected date is now highlighted in green,
* ````EarliestMonthSelectable```` and ````LatestMonthSelectable```` options have been added so that the range of months that can be picked can be restricted,
* The ````AlwaysShown```` option has been added, which keeps the picker displayed, allowing things like the month input field to be hidden, and an automatic submit on selection, and
* To prevent confusion, the currently-selected year title is now hidden when years rather than months are being selected (any problems with this?)

Demos at http://jsfiddle.net/rbate/L5qr28d0/
Repository at https://github.com/mrj/jquery-ui-month-picker

I can do a pull request once the changes get settled.

**Comment by KidSysco** [comment]
Wow I am totally blown away at this Mark! Great work! Somehow I knew that if I were to blow off all of these requests that someone might come in and do them! I am just kidding, really I am just busy and very grateful for your assistance!

This is outstanding work for the following reasons...

1. You looked through the forum to find things other folks wanted that you could implement while you were in there doing things for yourself... Very cool. I love the idea of the green selected month, the button color is CSS controlled, awesome. The date restrictions must have been the toughest part, very impressive work! Keeping the Picker visible is going to be useful, I can tell already. I have no issues with the year getting hidden at the right time, I think this provides another good UI indication of which mode the picker is in.

2. You forked the JS Fiddle, linked the original, provided a list of changes and demonstrations.

3. Since you forked the Fiddle, I can tell your changes did not break any existing Unit Tests, so we know things should be playing nicely.

Well Done!

For your hard work and contribution, I am very pleased to work with you and I will support whatever it is you need.

I could help put in a few unit test assertions if you need anything there, so many testing frameworks out there I know, but I think it is a great idea to get a couple of tests in the Fiddle. Let me know, this part is not required for a pull request, it's just for the JS Fiddle demo.

Let's continue to test it here and when you are comfortable, send me a Pull Request, I will bump and merge.

Please let me know if there is anything else you need.

-kid

**Comment by mrj** [comment]
Thanks kid for your kind comments. Though I'd read this thread beforehand, and so knew others wanted selection limits, my motivation was to implement the features I needed. I'm just glad there was such a nice widget on which to build, which saved me a lot of time.

I'll work on adding some test assertions on JSFiddle for the new features. I'm very glad you put together all those tests in the first place, because they exposed a few bugs in my code.

One further addition I think would be helpful would be to set the CSS so that users are made aware that the year title is a link, perhaps even with a tooltip that explains what clicking it does. Also disabling text selection on the title would prevent ugly highlighting when trying to click a button that has disappeared.

What made you choose to go back & forward 5 years with year paging, rather than a full 12-year page? I think there's merit in keeping years in the same position.

**Comment by KidSysco** [comment]
Hi Mark,

I really like every idea you have here. The year link could use a bit more work as you say.

And a 12 year paging routine... Yea, of course... I am trying to understand why I didn't think of that but I don't know... I just didn't I guess. But I think that idea is perfect.

**Comment by KidSysco** [comment]
Any updates on this?

**Comment by KidSysco** [comment]
Mrj's fork still exists, we might want to steal on a few of his ideas. I will leave this open for now.

**Comment by KidSysco** [comment]
I believe this was fixed thanks to Benjamin! Woot!
