### ISSUE TITLE
MonthPicker doesn't close when parent Dialog closes

### ISSUE THREAD

**Issue by jwcurnalia** [KidSysco/jquery-ui-month-picker#53]
If the MonthPicker is open when the user closes its parent Dialog, the MonthPicker remains on screen.

**Comment by benjamin-albert** [comment]
Thank you for bringing this up.

Stay tuned while I check jQuery UI's source to see what we can do about this.

**Comment by KidSysco** [comment]
I was able to do this in the fiddle...

$('#Modal').dialog({
    autoOpen: false,
    title: 'MonthPicker Dialog Test',
    modal: true,
	  close: function( event, ui ) {
  	$('body').trigger('click');
  }
});

**Comment by KidSysco** [comment]
One more thing about this Ben...

Instead of just clicking the body to hide the menu I originally wanted to just call our API for close...

$('.selector').MonthPicker('Close') 

But when I did that in the fiddle it did not seem to work. 

I still look forward to hearing about how this issue is normally dealt with in jQuery UI plugins.

**Comment by benjamin-albert** [comment]
I have'n looked at the code yet but I suspect this problem occurs because they call `event.stopPropagation()` on the close button's click event.

**Comment by benjamin-albert** [comment]
Looks like I've found the culprit, see: [ui/widgets/dialog.js#L438](
https://github.com/jquery/jquery-ui/blob/9644e7bae9116edaf8d37c5b38cb32b892f10ff6/ui/widgets/dialog.js#L438).

**Comment by benjamin-albert** [comment]
Looks like this is happening not just because jQuery UI calls `event.preventDefault()` but because we check if `event.isDefaultPrevented()` in [the Close() method](https://github.com/KidSysco/jquery-ui-month-picker/blob/2cc0d64955ca73dde70d942fabe614f93f2b3523/src/MonthPicker.js#L593).

I'm thinking we can clone the event and make sure `event.preventDefault()` was called from within the `OnBeforeMenuClose` event.
