### ISSUE TITLE
setting current month/year

### ISSUE THREAD

**Issue by dasguptahirak** [KidSysco/jquery-ui-month-picker#69]
Thanks for this nice api :+1: 

I want to set current month/year on load event of MonthPicker control.
How to do that?

This is the way I am trying:
`$('#select_month_year').MonthPicker({ Button: false }).MonthPicker('setDate',new Date());`

But its not working. Kindly help.

**Comment by KidSysco** [comment]
Hello dasguptahirak,

We can set the start year that the picker will default to when activated by the user by using the StartYear option...

https://github.com/KidSysco/jquery-ui-month-picker/wiki/StartYear-Option

like this...

`$('#select_month_year').MonthPicker({ StartYear: 2023 });`

If you wish to also set the default month, just set the value like this...

`$('#select_month_year').val('02/2023');`

Otherwise there is no way to select a default button at this point, but that doesn't seem like it would be too helpful anyway.

Let me know if this works for you.

Thanks!
