### ISSUE TITLE
Typo in MaxMonth Wiki

### ISSUE THREAD

**Issue by bsienn-khan** [KidSysco/jquery-ui-month-picker#70]
https://github.com/KidSysco/jquery-ui-month-picker/wiki/MaxMonth-Option

The min and max month wikis seems duplicate of each other.  The options parameter in example of maxmonth says minmonth.

**Comment by KidSysco** [comment]
Good catch! Thank you! I like it when the fixes are easy like this! lol

The wiki has been updated, closing this one out.

**Comment by bsienn-khan** [comment]
@KidSysco 
A little one more. Thanks for the plugin. I would love to see improved documentation, like live samples with relevant code snippets along. something like jquery does with its docs. If I were half the programmer like you, I would really love to participate and help.

![untitled](https://cloud.githubusercontent.com/assets/3149876/22503773/1925c892-e895-11e6-9dcc-ac99fbb643d9.png)

**Comment by KidSysco** [comment]
Thanks again for posting this, your curation helps a great deal!

You don't need to be a good programmer to contribute in many meaningful ways.

However, something is telling me that you are selling yourself short.

If you are interested in helping, we always have stuff around here that needs to get done, your idea for documentation is a fine one, there is just not enough time in the day to do everything we want. Let me know if you want to get a bit more involved.

**Comment by benjamin-albert** [comment]
@bsienn Thank you for opening an issue and helping is make this project better for everyone.

**Comment by bsienn-khan** [comment]
@KidSysco I would love to participate in this project. Let me know how I can be of help. You can contact me on adeel.cs@gmail.com

**Comment by KidSysco** [comment]
@benjamin-albert what do you think? @bsienn had mentioned adding examples to the docs like they do on the jQuery UI site. Take a look here.

https://jqueryui.com/draggable/

For every option they show a usable demo of that option working.

There are a lot of options here. So this is a lot of work. Which is why it has not been done.

If the docs were made like the Query UI docs, then we would not need our Wiki anymore I suppose. So we could probably do this in another branch that @bsienn could have for a while. Then when he is ready, he could submit a pull request to us.

Speaking of which, we could just give him a copy of the gh-pages branch, and just do it there.

I am just thinking out loud here, looking for ideas.

Let me know.

**Comment by KidSysco** [comment]
I was looking at it again. Our gh-pages branch is much like the jQuery ui demo pages, then our Wiki functions as their API documentation. So I guess our docs are fairly similar. ALthough I am open to ideas here, I'm not sure it is needed. Any input is appreciated. What about chasing down some of those open pull requests? Just another idea.
